use_default_settings: true
general:
  debug: false
  instance_name: Job Buddy local search
search:
  autocomplete: ""
  formats:
    - html
    - json
server:
  limiter: false
  public_instance: false
  image_proxy: false
outgoing:
  request_timeout: 5.0
  max_request_timeout: 8.0
